{{- range $app := .values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.projectname }}-{{ $app.appname }}
  namespace: argo
spec:
  project: {{ $app.projectname }}
  source:
    path: {{ $app.appname }}
    repoURL: 'https://github.com/Ricky-Envi/ArgoCDtest.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: {{ $app.projectname }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{ end -}}
